### PR TITLE
Add .soft file: genomics data, as used in Clustergram (Dash Bio).

### PR DESCRIPTION
**Pull request by mkcor**
Hi @nicolaskruchten and @shammamah,

Does that make any sense? Examples in `dash-docs` and tests in `dash-bio-utils` could point to genomics datasets made available over here.

To be consistent with the rest of the table, we would want a plot.ly version of the dendogram in question (not embedded in a Dash app)... What do you think?

### CODE REVIEW

**Comment by shammamah** [comment]
@mkcor This looks great! 

>To be consistent with the rest of the table, we would want a plot.ly version of the dendogram in question (not embedded in a Dash app)... What do you think?

I don't think this makes a lot of sense, since the components are not part of `plot.ly`. It might be a better idea to instead link to the gallery apps for each component. What do you think?

**Comment by mkcor** [comment]
Thank you for reviewing, @shammamah!

Well, I have already linked to the gallery app https://dash-bio.plotly.host/dash-clustergram/ under "Dash Bio" in the "Chart example" column... but I was wondering what I could/should do about "Open in Plotly" (was considering writing `NA` and your comment is reinforcing my idea).

**Comment by mkcor** [comment]
Now ready for final review, @shammamah. Thanks!

**Comment by mkcor** [comment]
@nicolaskruchten @shammamah may I merge? Then I'll be able to move forward with https://github.com/plotly/dash-bio-utils/pull/6, thanks!

**Pull request merged**
